import type { Metadata } from "next";
import "./globals.css";
import ClerkProviderWrapper from "./providers/clerk-provider";
import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en" className="mdl-js" suppressHydrationWarning>
        <body
          className={cn(
            "bg-background overscroll-none font-sans antialiased",
            fontVariables
          )}
          data-new-gr-c-s-check-loaded="14.1229.0"
          data-gr-ext-installed=""
        >
          {children}
        </body>
      </html>
    </ClerkProviderWrapper>
  );
}
